language: ruby
cache: bundler
rvm:
  - 2.5.7
  - 2.6.5

before_install:
  - yes | gem update --system --force
  - gem install bundler

notifications:
  email:
    on_failure: change
    on_success: never
